import type { ApiKeyPreset } from "../types/apiKeys";

export const API_KEY_PRESETS: ApiKeyPreset[] = [
  {
    description: "Optional explicit IAM access key for AWS MCP when local AWS CLI/profile auth is not enough.",
    group: "MCP",
    id: "mcp-aws-access-key-id",
    keyName: "AWS_ACCESS_KEY_ID",
    kind: "mcp",
    label: "AWS access key ID",
    service: "aws",
  },
  {
    description: "Optional explicit IAM secret for AWS MCP. Use least-privilege credentials.",
    group: "MCP",
    id: "mcp-aws-secret-access-key",
    keyName: "AWS_SECRET_ACCESS_KEY",
    kind: "mcp",
    label: "AWS secret access key",
    service: "aws",
  },
  {
    description: "Optional temporary AWS session token for AWS MCP.",
    group: "MCP",
    id: "mcp-aws-session-token",
    keyName: "AWS_SESSION_TOKEN",
    kind: "mcp",
    label: "AWS session token",
    service: "aws",
  },
  {
    description: "Required by the official Brave Search MCP server.",
    group: "MCP",
    id: "mcp-brave-api-key",
    keyName: "BRAVE_API_KEY",
    kind: "mcp",
    label: "Brave MCP API key",
    service: "brave-search",
  },
  {
    description: "Required by exa-mcp-server for local Exa search and fetch tools.",
    group: "MCP",
    id: "mcp-exa-api-key",
    keyName: "EXA_API_KEY",
    kind: "mcp",
    label: "Exa MCP API key",
    service: "exa",
  },
  {
    description: "Required for Firecrawl cloud MCP search, scrape, crawl, and extraction tools.",
    group: "MCP",
    id: "mcp-firecrawl-api-key",
    keyName: "FIRECRAWL_API_KEY",
    kind: "mcp",
    label: "Firecrawl MCP API key",
    service: "firecrawl",
  },
  {
    description: "Required by tavily-mcp for local search, extract, map, and crawl tools.",
    group: "MCP",
    id: "mcp-tavily-api-key",
    keyName: "TAVILY_API_KEY",
    kind: "mcp",
    label: "Tavily MCP API key",
    service: "tavily",
  },
  {
    description: "Browserbase service key for cloud browser MCP automation. Model-provider keys stay on the Models page.",
    group: "MCP",
    id: "mcp-browserbase-api-key",
    keyName: "BROWSERBASE_API_KEY",
    kind: "mcp",
    label: "Browserbase API key",
    service: "browserbase",
  },
  {
    description: "Browserbase project ID for Browserbase MCP automation sessions.",
    group: "MCP",
    id: "mcp-browserbase-project-id",
    keyName: "BROWSERBASE_PROJECT_ID",
    kind: "mcp",
    label: "Browserbase project ID",
    service: "browserbase",
  },
  {
    description: "Fallback Heroku auth token for direct Heroku MCP server setups when CLI login is not enough.",
    group: "MCP",
    id: "mcp-heroku-api-key",
    keyName: "HEROKU_API_KEY",
    kind: "mcp",
    label: "Heroku MCP API key",
    service: "heroku",
  },
  {
    description: "Pulumi Cloud token for Pulumi MCP deployment, stack, refresh, and resource-search tools.",
    group: "MCP",
    id: "mcp-pulumi-access-token",
    keyName: "PULUMI_ACCESS_TOKEN",
    kind: "mcp",
    label: "Pulumi access token",
    service: "pulumi",
  },
  {
    description: "Required for the local @stripe/mcp server.",
    group: "MCP",
    id: "mcp-stripe-secret",
    keyName: "STRIPE_SECRET_KEY",
    kind: "mcp",
    label: "Stripe restricted key",
    service: "stripe",
  },
  {
    description: "Optional Context7 remote MCP header for higher limits and private repository docs.",
    group: "MCP",
    id: "mcp-context7-api-key",
    keyName: "CONTEXT7_API_KEY",
    kind: "mcp",
    label: "Context7 API key",
    service: "context7",
  },
  {
    description: "Connection string option for MongoDB MCP.",
    group: "MCP",
    id: "mcp-mongodb-connection-string",
    keyName: "MDB_MCP_CONNECTION_STRING",
    kind: "mcp",
    label: "MongoDB connection string",
    service: "mongodb",
  },
  {
    description: "Atlas service account ID option for MongoDB MCP.",
    group: "MCP",
    id: "mcp-mongodb-client-id",
    keyName: "MDB_MCP_API_CLIENT_ID",
    kind: "mcp",
    label: "MongoDB Atlas client ID",
    service: "mongodb",
  },
  {
    description: "Atlas service account secret option for MongoDB MCP.",
    group: "MCP",
    id: "mcp-mongodb-client-secret",
    keyName: "MDB_MCP_API_CLIENT_SECRET",
    kind: "mcp",
    label: "MongoDB Atlas client secret",
    service: "mongodb",
  },
  {
    description: "Redis URL for @modelcontextprotocol/server-redis.",
    group: "MCP",
    id: "mcp-redis-url",
    keyName: "REDIS_URL",
    kind: "mcp",
    label: "Redis URL",
    service: "redis",
  },
  {
    description: "Bearer token for the GitHub remote MCP endpoint.",
    group: "MCP",
    id: "mcp-github-token",
    keyName: "Authorization",
    kind: "mcp",
    label: "GitHub MCP token",
    service: "github",
  },
  {
    description: "Personal access token for GitHub CLI, imported GitHub skills, or custom GitHub automation that cannot use desktop OAuth.",
    group: "Skill",
    id: "skill-github-token",
    keyName: "GITHUB_TOKEN",
    kind: "skill",
    label: "GitHub personal access token",
    service: "github",
  },
  {
    description: "Bearer token for the Cloudflare API MCP endpoint.",
    group: "MCP",
    id: "mcp-cloudflare-token",
    keyName: "Authorization",
    kind: "mcp",
    label: "Cloudflare API token",
    service: "cloudflare",
  },
  {
    description: "Personal access token fallback for direct Supabase MCP HTTP setups.",
    group: "MCP",
    id: "mcp-supabase-pat",
    keyName: "Authorization",
    kind: "mcp",
    label: "Supabase access token",
    service: "supabase",
  },
  {
    description: "Personal access token fallback for direct GitLab MCP or self-managed GitLab setups.",
    group: "MCP",
    id: "mcp-gitlab-token",
    keyName: "Authorization",
    kind: "mcp",
    label: "GitLab access token",
    service: "gitlab",
  },
  {
    description: "Bearer token fallback for direct Sentry MCP setups.",
    group: "MCP",
    id: "mcp-sentry-token",
    keyName: "Authorization",
    kind: "mcp",
    label: "Sentry auth token",
    service: "sentry",
  },
  {
    description: "Sentry API token name used by imported Sentry skills and direct API scripts.",
    group: "Skill",
    id: "skill-sentry-auth-token",
    keyName: "SENTRY_AUTH_TOKEN",
    kind: "skill",
    label: "Sentry auth token",
    service: "sentry",
  },
  {
    description: "Bearer token fallback for direct Vercel API or MCP setups.",
    group: "MCP",
    id: "mcp-vercel-token",
    keyName: "Authorization",
    kind: "mcp",
    label: "Vercel access token",
    service: "vercel",
  },
  {
    description: "Optional fallback token for @netlify/mcp when browser or CLI authentication fails.",
    group: "MCP",
    id: "mcp-netlify-personal-access-token",
    keyName: "NETLIFY_PERSONAL_ACCESS_TOKEN",
    kind: "mcp",
    label: "Netlify MCP personal access token",
    service: "netlify",
  },
  {
    description: "Required by @apify/actors-mcp-server for Actor discovery, runs, datasets, and Apify platform tools.",
    group: "MCP",
    id: "mcp-apify-token",
    keyName: "APIFY_TOKEN",
    kind: "mcp",
    label: "Apify API token",
    service: "apify",
  },
  {
    description: "Firebase CLI token fallback for imported Firebase skills or CI-style workflows. Prefer local Firebase CLI login for the official Firebase MCP.",
    group: "Skill",
    id: "skill-firebase-token",
    keyName: "FIREBASE_TOKEN",
    kind: "skill",
    label: "Firebase CLI token",
    service: "firebase",
  },
  {
    description: "Required workspace/team ID for the official Slack MCP server.",
    group: "MCP",
    id: "mcp-slack-team-id",
    keyName: "SLACK_TEAM_ID",
    kind: "mcp",
    label: "Slack team ID",
    service: "slack",
  },
  {
    description: "Optional channel allow-list for the official Slack MCP server.",
    group: "MCP",
    id: "mcp-slack-channel-ids",
    keyName: "SLACK_CHANNEL_IDS",
    kind: "mcp",
    label: "Slack channel IDs",
    service: "slack",
  },
  {
    description: "API key fallback for Linear automation or custom skill workflows.",
    group: "Skill",
    id: "skill-linear-api-key",
    keyName: "LINEAR_API_KEY",
    kind: "skill",
    label: "Linear API key",
    service: "linear",
  },
  {
    description: "Internal integration secret for Notion custom skills or direct API workflows.",
    group: "Skill",
    id: "skill-notion-secret",
    keyName: "NOTION_API_KEY",
    kind: "skill",
    label: "Notion integration secret",
    service: "notion",
  },
  {
    description: "Atlassian API token for custom Jira or Confluence skills.",
    group: "Skill",
    id: "skill-atlassian-api-token",
    keyName: "ATLASSIAN_API_TOKEN",
    kind: "skill",
    label: "Atlassian API token",
    service: "atlassian",
  },
  {
    description: "Hugging Face token for imported skills or MCP servers that call Hugging Face APIs.",
    group: "Skill",
    id: "skill-huggingface-token",
    keyName: "HUGGINGFACE_API_KEY",
    kind: "skill",
    label: "Hugging Face token",
    service: "hugging-face",
  },
  {
    description: "Netlify token for deployment or site-management skills.",
    group: "Skill",
    id: "skill-netlify-token",
    keyName: "NETLIFY_AUTH_TOKEN",
    kind: "skill",
    label: "Netlify auth token",
    service: "netlify",
  },
  {
    description: "Render API key for deployment or service-management skills.",
    group: "Skill",
    id: "skill-render-api-key",
    keyName: "RENDER_API_KEY",
    kind: "skill",
    label: "Render API key",
    service: "render",
  },
  {
    description: "Neon API key for database-management skills.",
    group: "Skill",
    id: "skill-neon-api-key",
    keyName: "NEON_API_KEY",
    kind: "skill",
    label: "Neon API key",
    service: "neon",
  },
  {
    description: "CircleCI token for CI inspection or pipeline skills.",
    group: "Skill",
    id: "skill-circleci-token",
    keyName: "CIRCLE_TOKEN",
    kind: "skill",
    label: "CircleCI token",
    service: "circleci",
  },
  {
    description: "Twilio Account SID for communication automation skills.",
    group: "Skill",
    id: "skill-twilio-account-sid",
    keyName: "TWILIO_ACCOUNT_SID",
    kind: "skill",
    label: "Twilio Account SID",
    service: "twilio",
  },
  {
    description: "Twilio auth token for communication automation skills.",
    group: "Skill",
    id: "skill-twilio-auth-token",
    keyName: "TWILIO_AUTH_TOKEN",
    kind: "skill",
    label: "Twilio auth token",
    service: "twilio",
  },
  {
    description: "Brave Search API key for app web search and research skills. Brave MCP uses BRAVE_API_KEY.",
    group: "Service",
    id: "service-brave-search",
    keyName: "BRAVE_SEARCH_API_KEY",
    kind: "service",
    label: "Brave Search API key",
    service: "brave-search",
  },
  {
    description: "Mapbox token for weather, map, and geospatial workflows.",
    group: "Service",
    id: "service-mapbox-token",
    keyName: "MAPBOX_ACCESS_TOKEN",
    kind: "service",
    label: "Mapbox access token",
    service: "mapbox",
  },
  {
    description: "Mapbox token name used by bundled Remotion map workflows.",
    group: "Skill",
    id: "skill-remotion-mapbox-token",
    keyName: "REMOTION_MAPBOX_TOKEN",
    kind: "skill",
    label: "Remotion Mapbox token",
    service: "remotion",
  },
  {
    description: "ElevenLabs key used by bundled Remotion voiceover workflows.",
    group: "Skill",
    id: "skill-elevenlabs-api-key",
    keyName: "ELEVENLABS_API_KEY",
    kind: "skill",
    label: "ElevenLabs API key",
    service: "elevenlabs",
  },
  {
    description: "Discord bot token for Discord app workflows.",
    group: "App",
    id: "app-discord-bot-token",
    keyName: "DISCORD_BOT_TOKEN",
    kind: "app",
    label: "Discord bot token",
    service: "discord",
  },
  {
    description: "Discord application ID for interaction endpoints, gateway registration, and imported Discord skills.",
    group: "App",
    id: "app-discord-application-id",
    keyName: "DISCORD_APPLICATION_ID",
    kind: "app",
    label: "Discord application ID",
    service: "discord",
  },
  {
    description: "Discord Ed25519 public key used to verify interaction requests.",
    group: "App",
    id: "app-discord-public-key",
    keyName: "DISCORD_PUBLIC_KEY",
    kind: "app",
    label: "Discord public key",
    service: "discord",
  },
  {
    description: "Discord incoming webhook URL for app notifications.",
    group: "App",
    id: "app-discord-webhook",
    keyName: "DISCORD_WEBHOOK_URL",
    kind: "app",
    label: "Discord webhook URL",
    service: "discord",
  },
  {
    description: "ngrok token for exposing local Discord webhook or gateway helpers.",
    group: "App",
    id: "app-ngrok-token",
    keyName: "NGROK_AUTHTOKEN",
    kind: "app",
    label: "ngrok auth token",
    service: "ngrok",
  },
  {
    description: "Google desktop OAuth client ID for Gmail, Calendar, Tasks, or imported Google skills.",
    group: "App",
    id: "app-google-client-id",
    keyName: "GOOGLE_OAUTH_CLIENT_ID",
    kind: "app",
    label: "Google OAuth client ID",
    service: "google",
  },
  {
    description: "Google desktop OAuth client secret for Gmail, Calendar, Tasks, or imported Google skills.",
    group: "App",
    id: "app-google-client-secret",
    keyName: "GOOGLE_OAUTH_CLIENT_SECRET",
    kind: "app",
    label: "Google OAuth client secret",
    service: "google",
  },
  {
    description: "Public GitHub OAuth App Client ID for Settings > GitHub device-flow sign-in. GitHub does not need a client secret for this flow.",
    group: "App",
    id: "app-github-oauth-client-id",
    keyName: "GITHUB_OAUTH_CLIENT_ID",
    kind: "app",
    label: "GitHub OAuth client ID",
    service: "github",
  },
  {
    description: "Slack bot token for Slack MCP, custom skills, or future app workflows.",
    group: "MCP",
    id: "mcp-slack-bot-token",
    keyName: "SLACK_BOT_TOKEN",
    kind: "mcp",
    label: "Slack bot token",
    service: "slack",
  },
  {
    description: "Slack app-level token for socket-mode or app-management skills.",
    group: "Skill",
    id: "skill-slack-app-token",
    keyName: "SLACK_APP_TOKEN",
    kind: "skill",
    label: "Slack app token",
    service: "slack",
  },
  {
    description: "Slack signing secret for imported Slack app or webhook verification skills.",
    group: "Skill",
    id: "skill-slack-signing-secret",
    keyName: "SLACK_SIGNING_SECRET",
    kind: "skill",
    label: "Slack signing secret",
    service: "slack",
  },
  {
    description: "Microsoft Entra tenant ID for Teams, SharePoint, Outlook, or Graph skills.",
    group: "Skill",
    id: "skill-microsoft-tenant-id",
    keyName: "MICROSOFT_TENANT_ID",
    kind: "skill",
    label: "Microsoft tenant ID",
    service: "microsoft",
  },
  {
    description: "Microsoft app client ID for Teams, SharePoint, Outlook, or Graph skills.",
    group: "Skill",
    id: "skill-microsoft-client-id",
    keyName: "MICROSOFT_CLIENT_ID",
    kind: "skill",
    label: "Microsoft client ID",
    service: "microsoft",
  },
  {
    description: "Microsoft app client secret for Teams, SharePoint, Outlook, or Graph skills.",
    group: "Skill",
    id: "skill-microsoft-client-secret",
    keyName: "MICROSOFT_CLIENT_SECRET",
    kind: "skill",
    label: "Microsoft client secret",
    service: "microsoft",
  },
  {
    description: "Box app client ID for Box document or storage skills.",
    group: "Skill",
    id: "skill-box-client-id",
    keyName: "BOX_CLIENT_ID",
    kind: "skill",
    label: "Box client ID",
    service: "box",
  },
  {
    description: "Box app client secret for Box document or storage skills.",
    group: "Skill",
    id: "skill-box-client-secret",
    keyName: "BOX_CLIENT_SECRET",
    kind: "skill",
    label: "Box client secret",
    service: "box",
  },
  {
    description: "Canva app client ID for Canva design or export skills.",
    group: "Skill",
    id: "skill-canva-client-id",
    keyName: "CANVA_CLIENT_ID",
    kind: "skill",
    label: "Canva client ID",
    service: "canva",
  },
  {
    description: "Canva app client secret for Canva design or export skills.",
    group: "Skill",
    id: "skill-canva-client-secret",
    keyName: "CANVA_CLIENT_SECRET",
    kind: "skill",
    label: "Canva client secret",
    service: "canva",
  },
  {
    description: "Figma personal access token for Code Connect publish workflows.",
    group: "Skill",
    id: "skill-figma-access-token",
    keyName: "FIGMA_ACCESS_TOKEN",
    kind: "skill",
    label: "Figma access token",
    service: "figma",
  },
  {
    description: "HeyGen API key for video-generation skills.",
    group: "Skill",
    id: "skill-heygen-api-key",
    keyName: "HEYGEN_API_KEY",
    kind: "skill",
    label: "HeyGen API key",
    service: "heygen",
  },
  {
    description: "HubSpot private app token for CRM skills.",
    group: "Skill",
    id: "skill-hubspot-access-token",
    keyName: "HUBSPOT_ACCESS_TOKEN",
    kind: "skill",
    label: "HubSpot access token",
    service: "hubspot",
  },
  {
    description: "Zotero API key for reference-library skills.",
    group: "Skill",
    id: "skill-zotero-api-key",
    keyName: "ZOTERO_API_KEY",
    kind: "skill",
    label: "Zotero API key",
    service: "zotero",
  },
  {
    description: "Zoom OAuth client ID for Zoom meeting or calendar skills.",
    group: "Skill",
    id: "skill-zoom-client-id",
    keyName: "ZOOM_CLIENT_ID",
    kind: "skill",
    label: "Zoom client ID",
    service: "zoom",
  },
  {
    description: "Zoom OAuth client secret for Zoom custom skills.",
    group: "Skill",
    id: "skill-zoom-client-secret",
    keyName: "ZOOM_CLIENT_SECRET",
    kind: "skill",
    label: "Zoom client secret",
    service: "zoom",
  },
];

export function getApiKeyPresetById(id: string) {
  return API_KEY_PRESETS.find((preset) => preset.id === id);
}
