use crate::commands;
use tauri::Manager;

/// Builds the Tauri app, registers shared command state, and exposes command handlers.
pub fn builder() -> tauri::Builder<tauri::Wry> {
    tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .manage(commands::auth::AuthState::default())
        .manage(commands::computer::files::ComputerFileIndexState::default())
        .manage(commands::discord::DiscordBridgeState::default())
        .manage(commands::github::GithubState::default())
        .manage(commands::terminal::TerminalState::default())
        .manage(commands::updates::AppUpdateState::default())
        .setup(|app| {
            if let Some(icon) = app.default_window_icon().cloned() {
                for window in app.webview_windows().values() {
                    window.set_icon(icon.clone())?;
                }
            }

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::agent_runs::agent_run_delete,
            commands::agent_runs::agent_run_save,
            commands::agent_runs::agent_runs_list,
            commands::auth::auth_create_account,
            commands::auth::auth_get_login_challenge,
            commands::auth::auth_get_state,
            commands::auth::auth_login,
            commands::auth::auth_logout,
            commands::app_info::get_app_info,
            commands::browser::browser_automation,
            commands::computer::files::computer_build_file_index,
            commands::computer::files::computer_delete_file,
            commands::computer::files::computer_get_default_workspace,
            commands::computer::files::computer_get_file_index_summary,
            commands::computer::files::computer_get_git_status,
            commands::computer::files::computer_git_init,
            commands::computer::files::computer_git_commit,
            commands::computer::files::computer_git_create_branch,
            commands::computer::files::computer_git_create_worktree,
            commands::computer::files::computer_git_push,
            commands::computer::files::computer_list_directory,
            commands::computer::files::computer_list_drives,
            commands::computer::files::computer_move_path,
            commands::computer::files::computer_pick_folder,
            commands::computer::files::computer_read_text_file,
            commands::computer::files::computer_search_file_index,
            commands::computer::files::computer_write_text_file,
            commands::database::gilbert_database_cleanup_legacy_storage,
            commands::database::gilbert_database_get_overview,
            commands::database::gilbert_database_load,
            commands::database::gilbert_database_reset,
            commands::database::gilbert_database_set_value,
            commands::database::gilbert_database_set_values,
            commands::discord::discord_bridge_send_interaction_response,
            commands::discord::discord_bridge_start,
            commands::discord::discord_bridge_status,
            commands::discord::discord_bridge_stop,
            commands::discord::discord_register_slash_command,
            commands::github::github_commit_files,
            commands::github::github_begin_device_login,
            commands::github::github_connect_token,
            commands::github::github_create_branch,
            commands::github::github_create_pull_request,
            commands::github::github_create_release,
            commands::github::github_disconnect,
            commands::github::github_dispatch_workflow,
            commands::github::github_generate_release_notes,
            commands::github::github_get_repository,
            commands::github::github_get_state,
            commands::github::github_list_branches,
            commands::github::github_list_repositories,
            commands::github::github_list_releases,
            commands::github::github_list_tree,
            commands::github::github_list_workflow_runs,
            commands::github::github_list_workflows,
            commands::github::github_open_device_login,
            commands::github::github_poll_device_login,
            commands::github::github_read_file,
            commands::github::github_search_code,
            commands::app_info::open_external_url,
            commands::settings::settings_get_user_config,
            commands::settings::settings_open_user_config,
            commands::settings::workspace_dependencies_diagnose,
            commands::settings::workspace_dependencies_reinstall,
            commands::terminal::terminal_create_session,
            commands::terminal::terminal_drain_session,
            commands::terminal::terminal_get_default_working_directory,
            commands::terminal::terminal_kill_session,
            commands::terminal::terminal_resize_session,
            commands::terminal::terminal_run_command,
            commands::terminal::terminal_write_session,
            commands::updates::app_update_check,
            commands::updates::app_update_install,
            commands::web::brave_search,
            commands::web::duckduckgo_search,
            commands::weather::weather_fetch_json
        ])
}
